
### event

POST {{baseUrl}}/track
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "payload":"eyJldmVudHMiOlt7ImV2ZW50X25hbWUiOiJwYWdlX3ZpZXciLCJldmVudF9pZCI6IjQ5NTM4YzJmLTVmMWUtNGY2Zi1hMmE3LTBhOWVjZTMwOTMwNCIsInRpbWVzdGFtcCI6IjIwMjQtMDEtMzFUMDU6NTM6MjkuMTQ5WiIsInBhcmFtcyI6eyJwYWdlX3RpdGxlIjoiSG9tZVNoYXJwIC0gUHJvamVjdCBEZXRhaWxzIGZvciBPcmNoaWQgVmFzdW5kaGFyYSIsInBhZ2VfbG9jYXRpb24iOiJodHRwOi8vbG9jYWxob3N0OjMwMDAvcHJvamVjdC9vcmNoaWQtdmFzdW5kaGFyYSJ9fSx7ImV2ZW50X25hbWUiOiJwcm9wZXJ0eV9kZXRhaWxzX3ZpZXdlZCIsImV2ZW50X2lkIjoiMTRkNWU3MDQtMTNiZi00YmY2LTgyZmMtNDgwYmI5ODA2YTFjIiwidGltZXN0YW1wIjoiMjAyNC0wMS0zMVQwNTo1MzoyOS43MTBaIiwicGFyYW1zIjp7InByb3BlcnR5X2lkIjoib3JjaGlkLXZhc3VuZGhhcmEiLCJwcm9wZXJ0eV9uYW1lIjoiT3JjaGlkIFZhc3VuZGhhcmEiLCJsb2NhdGlvbiI6IlNhbnRhY3J1eihXKSIsImJ1ZGdldF9taW4iOjk5MTM1NjAzMCwiYnVpbGRlcl9pZCI6Im9yY2hpZC1ncm91cC1tdW1iYWkiLCJidWlsZGVyX25hbWUiOiJPcmNoaWQgR3JvdXAgKE11bWJhaSkifX1dfQ=="
}
