export const featureList = [
  'Game Zone',
  'Laundry',
  'Observatory',
  'Swimming Pool',
  'Gym',
  'Rooftop Garden',
  'Parking',
  '24/7 Security',
  'Smart Home Technology',
  'Spa',
  'Balcony',
  'Pet-friendly',
  'Fitness Center',
  'High-speed Internet',
  'Elevator',
  'Central Heating',
  'Air Conditioning',
  'Community Lounge',
  'Barbecue Area',
  'Concierge Service',
  'Yoga Studio',
  'Media Room',
  'Business Center',
  'Movie Theater',
  'Kids Play Area',
  'Tennis Court',
  'Basketball Court',
  'Walking Trails',
  'Green Energy Solutions',
  'Energy-efficient Appliances',
  'High Ceilings',
  'Walk-in Closets',
  'Smart Locks',
  'Package Lockers',
  'Pet Wash Station',
  'Bike Storage',
  'Car Charging Stations',
  'Guest Suites',
  'Wine Cellar',
  'Library or Reading Room',
  'Bike Repair Station',
  'Outdoor Fireplace or Fire Pit',
  'Community Garden',
  'Zen Garden',
  'Sauna',
  'Hot Tub',
  'Pet Park',
  'Electric Vehicle (EV) Parking',
  'Dog Walking Services',
  'Bar or Lounge Area',
  'Private Dining Room',
  'Pet-Friendly Park',
  '24/7 Maintenance',
  'Secured Access',
  'Poolside Cabanas',
  'Game Lounge',
  'Art Studio',
  'Coffee Bar',
  'Cyber Cafe',
  'Parcel Lockers',
  'On-site Retail',
  'Virtual Fitness Classes',
  'Movie Screening Room',
  'Pet Agility Course',
  'Waterfront Views',
  'Golf Simulator',
  'Karaoke Room',
  'Rooftop Terrace',
  'Bus',
  'Train',
  'Subway',
  'Highway',
  'Metro',
  'Airport',
  'Public Transportation Access (Bus, Train, Subway)',
  'Walking Distance to Public Transport Hubs',
  'Nearby Highway Access',
  'Bike Lanes and Bike Sharing Stations',
  'Carpooling or Ride Share Services Availability',
  'Electric Scooter or Bike Rental Facilities',
  'Proximity to Airport or Airport Shuttle Service'
];
