### Import Projects

POST {{baseUrl}}/import/projects
Authorization: Bearer {{directusToken}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="projects.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< Projects.xlsx

--WebAppBoundary
Content-Disposition: form-data; name="startRow"
Content-Type: text/plain

2
--WebAppBoundary
Content-Disposition: form-data; name="endRow"
Content-Type: text/plain

5
--WebAppBoundary--


### Import Micro Markets

POST {{baseUrl}}/import/micro-markets
Authorization: Bearer {{directusToken}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="coordinates.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< coordinates.xlsx

--WebAppBoundary
Content-Disposition: form-data; name="startRow"
Content-Type: text/plain

2

--WebAppBoundary
Content-Disposition: form-data; name="endRow"
Content-Type: text/plain

5
--WebAppBoundary--


### Import Both Projects and Micro Markets

POST {{baseUrl}}/import/complete-data
Authorization: Bearer {{directusToken}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="projectFile"; filename="projects.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< Projects.xlsx

--WebAppBoundary
Content-Disposition: form-data; name="microMarketFile"; filename="coordinates.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< coordinates.xlsx

--WebAppBoundary
Content-Disposition: form-data; name="startRow"
Content-Type: text/plain

5

--WebAppBoundary
Content-Disposition: form-data; name="endRow"
Content-Type: text/plain

5
--WebAppBoundary--
